; Auto-generated by Boot, regenerate by executing: 'boot lein-generate'
(defproject
  collin/pulina
  "0.1.0-SNAPSHOT"
  :dependencies
  [[org.clojure/clojure "1.9.0-alpha17"]
   [org.clojure/clojurescript "1.9.671" :scope "test"]
   [org.clojure/core.async "0.3.443"]
   [collin/puu "0.2.0-SNAPSHOT"]
   [mount "0.1.10"]
   [http-kit "2.1.18"]
   [compojure "1.5.0"]
   [hiccup "1.0.5"]
   [garden "1.3.2"]
   [re-frame "0.9.4"]
   [ring-middleware-format "0.7.2"]
   [com.cognitect/transit-cljs "0.8.239"]
   [com.rpl/specter "0.9.2"]
   [com.taoensso/sente "1.11.0" :exclusions [com.taoensso/encore]]
   [com.taoensso/timbre "4.10.0"]
   [adzerk/boot-test "1.1.0" :scope "test"]
   [org.martinklepsch/boot-garden "1.3.0-0" :scope "test"]
   [adzerk/boot-cljs "1.7.48-5" :scope "test"]
   [adzerk/boot-reload "0.5.1" :scope "test"]
   [com.cemerick/piggieback "0.2.1" :scope "test"]
   [weasel "0.7.0" :scope "test"]
   [adzerk/boot-cljs-repl "0.3.0" :scope "test"]
   [org.clojure/tools.nrepl "0.2.12" :scope "test"]
   [crisptrutski/boot-cljs-test
    "0.2.2-20160812.063138-4"
    :scope
    "test"]
   [instaparse "1.4.1" :scope "test"]]
  :source-paths
  ["src/cljs" "src/cljc" "src/clj"]
  :test-paths
  ["test/clj" "test/cljs" "test/cljc"])